title:              SightCorner
email:              fucheng.zheng@gmail.com
description:        做一只有趣的灵魂在世界游荡
author:             Aaron Zheng
baseurl:            "/aaron-zheng"
url:                "https://aaron-zheng.github.io"

# Social Profiles
twitter_username:   aaronzheng_
github_username:    aaron-zheng
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  # - jekyll-feed
  # - jekyll-paginate
  # - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
